export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_DOGS_CREATE_USER = "GET_DOGS_CREATE_USER";
export const GET_DOGS_FOR_API = "GET_DOGS_FOR_API";
export const GET_DOGS_FOR_TEMP = "GET_DOGS_FOR_TEMP";
export const GET_DOGS_FOR_BREED = "GET_DOGS_FOR_BREED";
